---
- name: Create Gitlab Project
  hosts: localhost
  vars:
    gitlab_project:
      - DO274_Demo

  tasks:

    - name: Create Gitlab Project
      community.general.gitlab_project:
        api_url: https://git.lab.example.com/
        api_username: student
        api_password: Stud3nt123
        name: "{{ item }}"
        validate_certs: "false"
        visibility: public
      loop: "{{ gitlab_project }}"
