---
- name: Create Credentials
  hosts: localhost
  tasks:

    - name: Create SCM Credential
      ansible.controller.credential:
        name: "GitLab Projects"
        description: "Credentials for Built-In Gitlab"
        state: present
        organization: Red Hat Training
        credential_type: Source Control
        inputs:
          username: student
          password: Stud3nt123
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
 
