---
- name: Create Job Template
  hosts: localhost

  tasks:
### Create Job Workflow Template

    - name: Create Job Workflow Template - Service Restored
      ansible.controller.workflow_job_template:
        name: "DEMO - EDA Restoring HTTPD Service"
        organization: Red Hat Training
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present

### Run Job Template Nofitying Mattermost
    - name: Create Run Job Template - Notify Mattermost
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Notify MM
        workflow_job_template: "DEMO - EDA Restoring HTTPD Service"
        unified_job_template: "DO274 - Fix Service - MM"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false

### Run Job Template for Fixing HTTPD Service
    - name: Create Run Job Template - Fix HTTPD Service
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Service Restore
        workflow_job_template: "DEMO - EDA Restoring HTTPD Service"
        unified_job_template: "DO274 - Fix Service"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        success_nodes:
          - Notify MM