---
- name: Create Job Template
  hosts: localhost

  tasks:
### Create Job Workflow Template

    - name: Create Job Workflow Template - Index HTML Restored
      ansible.controller.workflow_job_template:
        name: "DEMO - EDA Restoring Index.html"
        organization: Red Hat Training
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present

### Run Job Template Nofitying Mattermost
    - name: Create Run Job Template - Notify Mattermost
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Notify MM
        workflow_job_template: "DEMO - EDA Restoring Index.html"
        unified_job_template: "DO274 - Fix Index - MM"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false

### Run Job Template for Fixing Index.html
    - name: Create Run Job Template - Fix Index.html
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Index Restore
        workflow_job_template: "DEMO - EDA Restoring Index.html"
        unified_job_template: "DO274 - Fix Index"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        success_nodes:
          - Notify MM