---
### Create Ansible Controller Demo
- import_playbook: Create_Organization.yml
- import_playbook: Create_Machine_Creds.yml
- import_playbook: Create_SCM_Creds.yml
- import_playbook: Create_Project.yml
- import_playbook: Setup_Inventory.yml
- import_playbook: Create_Job_Template.yml
- import_playbook: Create_Job_Template_Workflows_Index.yml
- import_playbook: Create_Job_Template_Workflows_Service.yml

### EDA Controller Setup
## Creating the project is not Idempotent

- import_playbook: Create_EDA_Project.yml
- import_playbook: Sync_EDA_Project.yml