---
- name: Display User and Sudo Changes
  hosts: all

  sources:
    #- name: Watch Sudoers File
    #  ansible.eda.file_watch:
    #    path: "/etc/sudoers"
    #    recursive: false

    - name: Watch Sudoers File in Drop-in Directory
      ansible.eda.file_watch:
        path: "/etc/sudoers.d"
        recursive: true
        #ignore_regexes: [ '.*\.o' ]

  rules:
#    - name: Display event information
#      condition: event.change == 'created'
#      action:
#        run_module:
#          name: ansible.builtin.debug
#          module_args:
#            msg: There was a change

#    - name: Print Output of what Changed Using Print Event
#      condition: event.change == 'created'
#      action:
#        print_event:
#          var_root: src_path

    - name: Print Output of what Changed
      condition: event.change == 'created'
      action:
        run_module:
          name: ansible.builtin.debug
          module_args:
            msg: The following file was changed {{ event.src_path }} 
