---
- name: Display User and Sudo Changes
  hosts: all

  sources:
    - name: Watch Sudoers File
      file_watch:
        path: /etc/sudoers
        recursive: false

    - name: Watch Sudoers File in Drop-in Directory
      file_watch:
        path: /etc/sudoers.d
        recursive: true

  rules:
    - name: Display event information
      condition: event.journald._comm in vars.identity_commands
      action:
        print_event:
           event_data: '{{ _event_raw }}'
