---
- name: Capture posted events from GitLab
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: R1 - Heard "Hello!"
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
