---
- name: Restoring website content
  hosts: servera
  remote_user: devops
  become: true
  gather_facts: false
  tasks:
    - name: Display a message
      ansible.builtin.debug:
        msg: "Website is down!"

    - name: Create an Index.HTML File
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html lang=”en”>
            <head>
              <title>Welcome to Red Hat Training</title>
            </head>
              <body>
                <p>This is a test page on Apache!!</p>
              </body>
          </html>
        dest: /var/www/html/index.html
