---
- name: start app
  gather_facts: False
  hosts: all
  tasks:
    - shell: /home/ec2-user/fastapi-realworld-example-app/run_app.sh & sleep 1
      async: 100000000
      poll: 0
    - wait_for:
        path: /home/ec2-user/fastapi-realworld-example-app/fact.yml
        state: present
    - fetch:
        src: /home/ec2-user/fastapi-realworld-example-app/fact.yml
        dest: fact.yml
        flat: true
    - include_vars:
        file: fact.yml
    - set_fact:
        cacheable: true
        pid: "{{pid}}"
    - pause:
        seconds: 10



...
