---
- hosts: localhost
  gather_facts: False
  tasks:
    - shell:
        cmd: pytest -v
        chdir: "{{src_path}}"
      register: test_result
      ignore_errors: yes
    - set_fact:
        cacheable: true
        output: "{{test_result.stdout}}"
        returncode: "{{test_result.rc}}"
...
